# Generated by Django 5.1 on 2024-08-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicpassenger',
            name='embarked',
            field=models.CharField(max_length=10),
        ),
    ]
